"""SQLAlchemy models, one module per aggregate.

Importing this package registers every table on ``app.database.Base.metadata``,
which is what Alembic's ``env.py`` and the seed rely on.
"""

from app.models.agenda import BloqueoFranja, DiaNoLaborable, HorarioAtencion
from app.models.asignacion import AsignacionServicio, ColaEspera
from app.models.autenticacion import (
    IntentoLogin,
    TokenRecuperacion,
    TokenRefresco,
    VerificacionCorreo,
)
from app.models.bahia import MAXIMO_BAHIAS, Bahia
from app.models.calidad import Calificable, Calificacion, Evidencia
from app.models.enums import (
    CENTIMOS_POR_PUNTO,
    ESTADOS_CUENTA_CON_ACCESO,
    ESTADOS_PAGO_COBRADO,
    ESTADOS_PAGO_INGRESADO,
    FACTOR_BASE_MILESIMAS,
    MEDIOS_EN_LINEA,
    MEDIOS_PRESENCIALES,
    MONEDA_PREDETERMINADA,
    PUNTOS_LAVADO_BASICO,
    PUNTUACION_MAXIMA,
    PUNTUACION_MINIMA,
    RANGO_MAXIMO_DIAS,
    CanalNotificacion,
    CarpetaArchivo,
    EstadoBahia,
    EstadoCargaEvidencia,
    EstadoComprobante,
    EstadoCuenta,
    EstadoCupon,
    EstadoEnvio,
    EstadoExportacion,
    EstadoPago,
    EstadoRecordatorio,
    EstadoReembolso,
    EstadoReserva,
    EstadoTransaccion,
    EventoNotificacion,
    FormatoReporte,
    Idioma,
    MedioPago,
    ModalidadPago,
    MomentoEvidencia,
    MotivoBloqueo,
    OperacionPasarela,
    PlataformaDispositivo,
    RespuestaRecordatorio,
    TipoDescuento,
    TipoDocumento,
    TipoMovimientoPuntos,
    TipoReembolso,
    TipoReporte,
    TipoVehiculo,
)
from app.models.evento import EventoDominio
from app.models.fidelizacion import Beneficio, CuponCanje, PuntosMovimiento
from app.models.notificacion import (
    VENTANA_RECORDATORIO,
    Dispositivo,
    Notificacion,
    PlantillaNotificacion,
    Recordatorio,
)
from app.models.pago import Comprobante, Pago, Reembolso, TransaccionPasarela
from app.models.reporte import ReporteExportacion
from app.models.reserva import Reserva, ReservaEstadoHistorial, TransicionEstado
from app.models.rol import Permiso, Rol, RolPermiso
from app.models.servicio import Servicio, ServicioPrecio
from app.models.tarifa import (
    FactorTipoVehiculo,
    Paquete,
    PaqueteServicio,
    Promocion,
    ReservaAdicional,
    ReservaTarifaDesglose,
    ServicioAdicional,
)
from app.models.usuario import Usuario
from app.models.vehiculo import Vehiculo

__all__ = [
    "CENTIMOS_POR_PUNTO",
    "ESTADOS_CUENTA_CON_ACCESO",
    "ESTADOS_PAGO_COBRADO",
    "ESTADOS_PAGO_INGRESADO",
    "FACTOR_BASE_MILESIMAS",
    "MAXIMO_BAHIAS",
    "MEDIOS_EN_LINEA",
    "MEDIOS_PRESENCIALES",
    "MONEDA_PREDETERMINADA",
    "PUNTOS_LAVADO_BASICO",
    "VENTANA_RECORDATORIO",
    "PUNTUACION_MAXIMA",
    "PUNTUACION_MINIMA",
    "RANGO_MAXIMO_DIAS",
    "AsignacionServicio",
    "Bahia",
    "Beneficio",
    "BloqueoFranja",
    "Calificable",
    "Calificacion",
    "CanalNotificacion",
    "CarpetaArchivo",
    "ColaEspera",
    "Comprobante",
    "CuponCanje",
    "DiaNoLaborable",
    "Dispositivo",
    "EstadoBahia",
    "EstadoCargaEvidencia",
    "EstadoComprobante",
    "EstadoCuenta",
    "EstadoCupon",
    "EstadoEnvio",
    "EstadoExportacion",
    "EstadoPago",
    "EstadoRecordatorio",
    "EstadoReembolso",
    "EstadoReserva",
    "EstadoTransaccion",
    "EventoDominio",
    "EventoNotificacion",
    "Evidencia",
    "FactorTipoVehiculo",
    "FormatoReporte",
    "HorarioAtencion",
    "Idioma",
    "IntentoLogin",
    "MedioPago",
    "ModalidadPago",
    "MomentoEvidencia",
    "MotivoBloqueo",
    "Notificacion",
    "OperacionPasarela",
    "Pago",
    "Paquete",
    "PaqueteServicio",
    "Permiso",
    "PlantillaNotificacion",
    "PlataformaDispositivo",
    "Promocion",
    "PuntosMovimiento",
    "Recordatorio",
    "Reembolso",
    "ReporteExportacion",
    "Reserva",
    "ReservaAdicional",
    "ReservaEstadoHistorial",
    "ReservaTarifaDesglose",
    "RespuestaRecordatorio",
    "Rol",
    "RolPermiso",
    "Servicio",
    "ServicioAdicional",
    "ServicioPrecio",
    "TipoDescuento",
    "TipoDocumento",
    "TipoMovimientoPuntos",
    "TipoReembolso",
    "TipoReporte",
    "TipoVehiculo",
    "TokenRecuperacion",
    "TokenRefresco",
    "TransaccionPasarela",
    "TransicionEstado",
    "Usuario",
    "Vehiculo",
    "VerificacionCorreo",
]
